import type { LanguageTarget, LearnerNativeLanguage } from "../types";

export type UiLanguage = "en" | "es";

export function getUiLanguage(languageTarget: LanguageTarget, learnerNativeLanguage?: LearnerNativeLanguage): UiLanguage {
  if (learnerNativeLanguage === "spanish") return "es";
  if (learnerNativeLanguage === "english") return "en";
  return languageTarget === "english" ? "es" : "en";
}

const copy = {
  en: {
    activity: "Activity",
    minutes: "min",
    start: "Start",
    check: "Check",
    next: "Next",
    finish: "Finish",
    finishDrill: "Finish drill",
    answer: "Answer",
    yourAnswer: "Your answer",
    typeAnswer: "Type your answer...",
    correct: "Correct.",
    incorrect: "Incorrect.",
    almost: "Almost correct.",
    almostCheckPunctuation: "Almost correct. Check the punctuation.",
    almostCheckAccents: "Almost correct. Check the accent marks.",
    incorrectReviewAnswer: "Incorrect. Review the correct answer and try it again later.",
    showAnswer: "Show answer",
    hint: "Hint",
    nativeMeaning: "Meaning in your language",
    targetPrompt: "Target language",
    instructions: "What to do",
    specialChars: "Use these buttons if your keyboard is missing accents or punctuation.",
    returnSkool: "Return to Skool",
    grammarProgress: "Grammar progress",
    review: "Review the feedback, then continue.",
    verbGuide: "Choose a tense and person, type the correct conjugation, then check your answer.",
    quizGuide: "Answer the question first. For typed questions, press Check before moving on.",
    readingGuide: "Read the text, answer each question type, then check your comprehension.",
    storyGuide: "Reveal messages one by one. Answer comprehension checks when they appear.",
    sentenceGuide: "Study the new words, speak first, type your translation, then shadow the model answer.",
    flashcardGuide: "Flashcards help you memorise vocabulary. First, look at the Spanish card and try to remember the English meaning. Click the card to check yourself. Use Still learning if you missed it, Know if you remembered it. Then use recall practice to test yourself.",
    answerPlaceholder: "Type your answer...",
    conjugation: "Conjugation",
    typeConjugation: "Type the conjugation...",
    tense: "Tense",
    person: "Person",
    nextPrompt: "Next prompt",
    finishQuiz: "Finish quiz",
    checkAnswers: "Check answers",
    comprehension: "Comprehension",
    storyControls: "Story controls",
    showTranslations: "Show translations",
    autoplay: "Auto-play",
    readAloud: "Read messages aloud",
    restartStory: "Restart story",
    continueStory: "Continue story",
    revealNextMessage: "Reveal next message",
    comprehensionCheck: "Comprehension check",
    deckMastery: "Deck mastery",
    activityProgress: "Activity progress",
    lessonComplete: "Lesson complete",
    bridgeCrossed: "Nice work. Bridge crossed.",
    returnCommunityMessage: "Return to PU3NTE Community and continue with the next Skool lesson.",
    readyToStart: "Ready to start",
    seeResults: "See results",
    newVocabulary: "New Vocabulary",
    stepTry: "Step 1: study the new words, then type your translation.",
    stepChecked: "Step 2: review the model answer and listen carefully.",
    stepShadow: "Step 3: shadow the sentence aloud before continuing.",
    noTimer: "No timer",
    newWordsTip: "New words · tap the info icon for a mini guide",
    speakThenType: "Speak your best attempt first, then type it. Use the character buttons if your keyboard is missing accents or Spanish punctuation.",
    yourTranslation: "Your translation",
    typeTranslation: "Type your translation...",
    showMixedVocab: "Need help? Show mixed vocab",
    mixedVocabShown: "Mixed vocab shown",
    mixedVocabBank: "Mixed vocabulary bank",
    acceptedRemember: "Accepted, with one thing to remember.",
    notQuiteYet: "Not quite yet.",
    shadowingStep: "Shadowing step",
    shadowInstruction: "Listen to the model answer, then repeat it aloud with the same rhythm before moving on.",
    playAudioAgain: "Play answer audio again",
    shadowedIt: "I shadowed it",
    continueNextStage: "Continue to next stage",
    markForPractice: "Mark for practice",
    iWasCorrect: "I was correct",
    dontKnow: "I don't know",
    front: "Front",
    back: "Back",
    flipFlashcard: "Flip flashcard",
    stillLearning: "Still learning",
    know: "Know",
    flashcardShortcuts: "Shortcuts: space flips, 1 marks learning, 2 marks know.",
    reviewFlashcards: "Review flashcards",
    practiceRecall: "Learn mode",
    reviewFlashcardsHelp: "Tap each card, check the meaning, then choose Know or Still learning.",
    practiceRecallHelp: "After reviewing, answer quiz-style questions without seeing the answer first.",
    flashcardReviewStepFront: "Step 1: read the Spanish. Try to say the English meaning before you flip.",
    flashcardReviewStepBack: "Step 2: check the English meaning and example. Choose whether you knew it.",
    englishMeaning: "English meaning",
    exampleInSpanish: "Example in Spanish",
    exampleInEnglish: "English translation",
    tapCardToFlip: "Tap card to flip",
    startRecallPractice: "Start recall practice",
    done: "Done",
    flashcardReviewComplete: "Card review complete",
    flashcardReviewMissedSummary: "You marked {count} card(s) as Still learning. Review only those cards, or move on to recall practice.",
    flashcardReviewNoMisses: "You marked every card as Know. Great — now move on to recall practice.",
    reviewStillLearning: "Review Still learning cards",
    moveToLearnMode: "Move on to Learn mode",
    studySettings: "Study Settings",
    studySettingsHelp: "Optional: you can ignore these. They only change how the practice quiz behaves.",
    direction: "Direction",
    termToDefinition: "Term to definition",
    definitionToTerm: "Definition to term",
    random: "Random",
    accentSensitivity: "Accent sensitivity",
    strict: "Strict",
    forgiving: "Forgiving",
    ignore: "Ignore",
    punctuation: "Punctuation",
    multipleChoice: "Multiple choice",
    typedRecall: "Typed recall",
    shuffleCards: "Shuffle cards",
    starredOnly: "Starred only",
    resetDeckProgress: "Reset this deck progress",
    chooseMatch: "Choose the match",
    correctAnswer: "Correct answer",
    sessionResults: "Session Results",
    mastered: "Mastered",
    accuracy: "Accuracy",
    missedCards: "Missed cards",
    retryMissedCards: "Retry missed cards",
    finishReturnSkool: "Finish and return to Skool",
    focusMode: "Focus mode",
    showTranslation: "Show translation",
    hideTranslation: "Hide translation",
    shadow: "Shadow",
    tapWordTiles: "Tap word tiles below to build the sentence.",
    checkpointPassed: "Checkpoint passed",
    keepPracticing: "Keep practicing",
    score: "Score",
    celebration: "A little celebration glow, saved locally.",
    retryQuiz: "Retry quiz",
    reviewMistakes: "Review mistakes",
    point: "point",
    matchPairsGuide: "Tap a word on the left, then tap its match on the right. Correct pairs lock into matching colors.",
    matched: "matched",
    allPairsMatched: "Correct. All pairs matched.",
    question: "Question",
    niceMatch: "Nice match.",
    understandPattern: "Understand the pattern",
    grammarSnapshot: "Grammar Snapshot",
    startPractice: "Start practice",
    grammarResults: "Grammar results",
    sections: "Sections",
    strongestArea: "Strongest area",
    weakTags: "Weak tags",
    mistakesReview: "Mistakes review",
    retryWeakAreas: "Retry weak areas",
    restartLesson: "Restart lesson",
    miniGuide: "Mini guide",
    closeMiniGuide: "Close mini guide",
    examples: "Examples",
    backToSentence: "Back to sentence",
    storyComplete: "Story Complete",
    learnedPhrases: "Learned phrases",
    addVocabularyLater: "Add vocabulary later.",
    practiceStoryFlashcards: "Practice flashcards from this story",
    messages: "messages",
    weakSpots: "Weak spots",
    noWeakSpots: "No weak verbs or tenses yet.",
    misses: "misses",
    commonMistake: "Common mistake",
    step: "Step",
    new: "new",
    learning: "learning",
    reviewing: "reviewing",
    masteredStatus: "mastered",
  },
  es: {
    activity: "Actividad",
    minutes: "min",
    start: "Empezar",
    check: "Revisar",
    next: "Siguiente",
    finish: "Terminar",
    finishDrill: "Terminar práctica",
    answer: "Respuesta",
    yourAnswer: "Tu respuesta",
    typeAnswer: "Escribe tu respuesta...",
    correct: "Correcto.",
    incorrect: "Incorrecto.",
    almost: "Casi correcto.",
    almostCheckPunctuation: "Casi correcto. Revisa la puntuación.",
    almostCheckAccents: "Casi correcto. Revisa los acentos.",
    incorrectReviewAnswer: "Incorrecto. Revisa la respuesta correcta e inténtalo otra vez después.",
    showAnswer: "Mostrar respuesta",
    hint: "Pista",
    nativeMeaning: "Significado en tu idioma",
    targetPrompt: "Idioma objetivo",
    instructions: "Qué hacer",
    specialChars: "Usa estos botones si tu teclado no tiene acentos o puntuación.",
    returnSkool: "Volver a Skool",
    grammarProgress: "Progreso de gramática",
    review: "Revisa la retroalimentación y después continúa.",
    verbGuide: "Elige un tiempo y una persona, escribe la conjugación correcta y revisa tu respuesta.",
    quizGuide: "Responde primero. En preguntas escritas, pulsa Revisar antes de continuar.",
    readingGuide: "Lee el texto, responde cada tipo de pregunta y luego revisa tu comprensión.",
    storyGuide: "Revela los mensajes uno por uno. Responde las preguntas de comprensión cuando aparezcan.",
    sentenceGuide: "Estudia las palabras nuevas, habla primero, escribe tu traducción y luego repite el modelo.",
    flashcardGuide: "Las tarjetas te ayudan a memorizar vocabulario. Primero mira la tarjeta en inglés e intenta recordar el significado en español. Toca la tarjeta para comprobar. Usa Todavía estoy aprendiendo si fallaste, o Lo sabía si lo recordaste. Después usa la práctica de memoria para ponerte a prueba.",
    answerPlaceholder: "Escribe tu respuesta...",
    conjugation: "Conjugación",
    typeConjugation: "Escribe la conjugación...",
    tense: "Tiempo",
    person: "Persona",
    nextPrompt: "Siguiente prompt",
    finishQuiz: "Terminar quiz",
    checkAnswers: "Revisar respuestas",
    comprehension: "Comprensión",
    storyControls: "Controles de historia",
    showTranslations: "Mostrar traducciones",
    autoplay: "Reproducción automática",
    readAloud: "Leer mensajes en voz alta",
    restartStory: "Reiniciar historia",
    continueStory: "Continuar historia",
    revealNextMessage: "Mostrar siguiente mensaje",
    comprehensionCheck: "Pregunta de comprensión",
    deckMastery: "Dominio del mazo",
    activityProgress: "Progreso de la actividad",
    lessonComplete: "Lección completa",
    bridgeCrossed: "Buen trabajo. Puente cruzado.",
    returnCommunityMessage: "Vuelve a la comunidad PU3NTE y continúa con la siguiente lección de Skool.",
    readyToStart: "Listo para empezar",
    seeResults: "Ver resultados",
    newVocabulary: "Vocabulario nuevo",
    stepTry: "Paso 1: estudia las palabras nuevas y después escribe tu traducción.",
    stepChecked: "Paso 2: revisa la respuesta modelo y escucha con atención.",
    stepShadow: "Paso 3: repite la frase en voz alta antes de continuar.",
    noTimer: "Sin temporizador",
    newWordsTip: "Palabras nuevas · toca el icono de información para ver una mini guía",
    speakThenType: "Di tu mejor intento primero y después escríbelo. Usa los botones de caracteres si tu teclado no tiene acentos o puntuación española.",
    yourTranslation: "Tu traducción",
    typeTranslation: "Escribe tu traducción...",
    showMixedVocab: "¿Necesitas ayuda? Mostrar vocabulario mezclado",
    mixedVocabShown: "Vocabulario mezclado visible",
    mixedVocabBank: "Banco de vocabulario mezclado",
    acceptedRemember: "Aceptado, con una cosa para recordar.",
    notQuiteYet: "Todavía no.",
    shadowingStep: "Paso de repetición",
    shadowInstruction: "Escucha la respuesta modelo y repítela en voz alta con el mismo ritmo antes de continuar.",
    playAudioAgain: "Reproducir audio otra vez",
    shadowedIt: "Ya lo repetí",
    continueNextStage: "Continuar a la siguiente etapa",
    markForPractice: "Marcar para practicar",
    iWasCorrect: "Yo estaba correcto/a",
    dontKnow: "No lo sé",
    front: "Frente",
    back: "Reverso",
    flipFlashcard: "Voltear tarjeta",
    stillLearning: "Todavía estoy aprendiendo",
    know: "Lo sé",
    flashcardShortcuts: "Atajos: espacio voltea, 1 marca aprendiendo, 2 marca sabido.",
    reviewFlashcards: "Repasar tarjetas",
    practiceRecall: "Modo Aprender",
    reviewFlashcardsHelp: "Toca cada tarjeta, revisa el significado y elige Lo sé o Todavía estoy aprendiendo.",
    practiceRecallHelp: "Después de repasar, responde preguntas tipo quiz sin ver primero la respuesta.",
    flashcardReviewStepFront: "Paso 1: lee el inglés. Intenta decir el significado en español antes de voltear.",
    flashcardReviewStepBack: "Paso 2: revisa el significado y el ejemplo. Elige si lo sabías.",
    englishMeaning: "Significado en inglés",
    exampleInSpanish: "Ejemplo en español",
    exampleInEnglish: "Traducción al inglés",
    tapCardToFlip: "Toca para voltear",
    startRecallPractice: "Empezar práctica de memoria",
    done: "Listo",
    flashcardReviewComplete: "Repaso de tarjetas completo",
    flashcardReviewMissedSummary: "Marcaste {count} tarjeta(s) como Todavía estoy aprendiendo. Repasa solo esas tarjetas o pasa a la práctica de memoria.",
    flashcardReviewNoMisses: "Marcaste todas las tarjetas como Lo sé. Muy bien: ahora pasa a la práctica de memoria.",
    reviewStillLearning: "Repasar tarjetas difíciles",
    moveToLearnMode: "Pasar al modo Aprender",
    studySettings: "Ajustes de estudio",
    studySettingsHelp: "Opcional: puedes ignorar esto. Solo cambia cómo aparece la práctica.",
    direction: "Dirección",
    termToDefinition: "Término a definición",
    definitionToTerm: "Definición a término",
    random: "Aleatorio",
    accentSensitivity: "Sensibilidad de acentos",
    strict: "Estricto",
    forgiving: "Flexible",
    ignore: "Ignorar",
    punctuation: "Puntuación",
    multipleChoice: "Opción múltiple",
    typedRecall: "Respuesta escrita",
    shuffleCards: "Mezclar tarjetas",
    starredOnly: "Solo destacadas",
    resetDeckProgress: "Reiniciar progreso de este mazo",
    chooseMatch: "Elige la pareja",
    correctAnswer: "Respuesta correcta",
    sessionResults: "Resultados de la sesión",
    mastered: "Dominadas",
    accuracy: "Precisión",
    missedCards: "Tarjetas falladas",
    retryMissedCards: "Reintentar tarjetas falladas",
    finishReturnSkool: "Terminar y volver a Skool",
    focusMode: "Modo enfoque",
    showTranslation: "Mostrar traducción",
    hideTranslation: "Ocultar traducción",
    shadow: "Repetir",
    tapWordTiles: "Toca las fichas de palabras para construir la frase.",
    checkpointPassed: "Checkpoint aprobado",
    keepPracticing: "Sigue practicando",
    score: "Puntuación",
    celebration: "Brillo de celebración guardado localmente.",
    retryQuiz: "Reintentar quiz",
    reviewMistakes: "Revisar errores",
    point: "punto",
    matchPairsGuide: "Toca una palabra de la izquierda y luego su pareja de la derecha. Las parejas correctas quedan bloqueadas con el mismo color.",
    matched: "emparejado",
    allPairsMatched: "Correcto. Todas las parejas están completas.",
    question: "Pregunta",
    niceMatch: "Buena pareja.",
    understandPattern: "Entiende el patrón",
    grammarSnapshot: "Resumen de gramática",
    startPractice: "Empezar práctica",
    grammarResults: "Resultados de gramática",
    sections: "Secciones",
    strongestArea: "Área más fuerte",
    weakTags: "Etiquetas débiles",
    mistakesReview: "Repaso de errores",
    retryWeakAreas: "Reintentar áreas débiles",
    restartLesson: "Reiniciar lección",
    miniGuide: "Mini guía",
    closeMiniGuide: "Cerrar mini guía",
    examples: "Ejemplos",
    backToSentence: "Volver a la frase",
    storyComplete: "Historia completa",
    learnedPhrases: "Frases aprendidas",
    addVocabularyLater: "Agrega vocabulario después.",
    practiceStoryFlashcards: "Practicar flashcards de esta historia",
    messages: "mensajes",
    weakSpots: "Puntos débiles",
    noWeakSpots: "Todavía no hay verbos o tiempos débiles.",
    misses: "fallos",
    commonMistake: "Error común",
    step: "Paso",
    new: "nueva",
    learning: "aprendiendo",
    reviewing: "repasando",
    masteredStatus: "dominada",
  },
} satisfies Record<UiLanguage, Record<string, string>>;

export function uiText(language: UiLanguage) {
  return copy[language];
}
